### ISSUE TITLE
Compile C# in Kali (Debian)?

### ISSUE THREAD

**Issue by xajyvi** [hlldz/SpookFlare#5]
Hello, can you assist with compiling the .cs files using some Linux variant? I think it can be done using `mono` [as seen here](https://www.c-sharpcorner.com/uploadfile/kirtan007/compile-C-Sharp-program-on-linux-operating-system/) but MonoDevelop crashes when I try importing .cs files. Any ideas?

**Comment by xajyvi** [comment]
@hlldz, I've tried a bunch of Google searches, but not having much luck. Any advice would be valued.

**Comment by hlldz** [comment]
Hi,

I would especially recommend compiling with csc.exe or Visual Studio. Because security products can have compiler-specific signatures, and the use of compilers in Linux distributions is ironically flagged as malicious.

I will also investigate situation, could you share screenshot or any output.
